export { default as Navbar } from './Navbar/Navbar'
export { default as Hero } from './Hero/Hero'
export { default as Info } from './InfoSection/Info'
export { default as Work } from './Work/Work'
export { default as Footer } from './Footer/Footer'
